In [51]:
import pandas as pd

In [52]:
import numpy as np

In [30]:
pd.__version__

'2.3.1'

In [31]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [32]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [61]:
df.shape

(9704, 11)

In [33]:
df.count()


engine_displacement    9704
num_cylinders          9222
horsepower             8996
vehicle_weight         9704
acceleration           8774
model_year             9704
origin                 9704
fuel_type              9704
drivetrain             9704
num_doors              9202
fuel_efficiency_mpg    9704
dtype: int64

In [34]:
df["fuel_type"].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [35]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [63]:
df["fuel_efficiency_mpg"].describe()

count    9704.000000
mean       14.985243
std         2.556468
min         6.200971
25%        13.267459
50%        15.006037
75%        16.707965
max        25.967222
Name: fuel_efficiency_mpg, dtype: float64

In [37]:
befor_median = df['horsepower'].median()
print(f"Original median of horsepower: {befor_median}")

Original median of horsepower: 149.0


In [38]:
most_frequent = df['horsepower'].mode()[0]
print(f"Most frequent value of horsepower: {most_frequent}")

Most frequent value of horsepower: 152.0


In [39]:
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [40]:
after_median = df['horsepower'].median()
print(f"Original median of horsepower: {after_median}")

Original median of horsepower: 152.0


In [44]:
selected_data=df[df['origin'] == 'Asia'][["vehicle_weight" , "model_year"]]
the_first_7 = selected_data.head(7)

In [45]:
the_first_7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [47]:
X = the_first_7.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [49]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [54]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [56]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [58]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [60]:
result_sum = w.sum()
result_sum

np.float64(0.5187709081074016)